---
name: "Build"
on:
  "pull_request"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - name: "install Nix"
        uses: "cachix/install-nix-action@v12"

      - name: "build doorgeefluik"
        run: "nix-build"
